### ISSUE TITLE
Getting rid of seams on test client

### ISSUE THREAD

**Issue by rsignell-usgs** [sci-wms/sci-wms#50]
I set min,max limits in the interface:
![7-10-2015 10-08-52 am](https://cloud.githubusercontent.com/assets/1872600/8620180/d9f654be-26eb-11e5-9f9a-d7998908070f.png)
but I still see seams:
![7-10-2015 9-45-27 am](https://cloud.githubusercontent.com/assets/1872600/8620194/0048a608-26ec-11e5-8517-fc24a848557d.jpg)

**Comment by kwilcox** [comment]
If you bump that min limit to 0.01, it will work.  Its a bug that I just fixed, but I'm not going to deploy right before your demo!

**Comment by rsignell-usgs** [comment]
I still see seams when I zoom out and in, but they are not as bad. 
![7-10-2015 12-03-43 pm](https://cloud.githubusercontent.com/assets/1872600/8622913/10dfda30-26fc-11e5-9942-f4ea2002f3f0.png)

**Comment by kwilcox** [comment]
It is not a color issue but an issue with the size of the vectors: see #51
